### PR TITLE
feat: add sort type th, highlight tr,interactive state, sticky header, variants th/td,numeric td

### PR DESCRIPTION
**Pull request by DiRaiks**
table

### CODE REVIEW

**Review by karinamaulitova — COMMENTED** [review]
Looks good, but sorting doesn't work, or maybe the stories example is not correct, and we can’t see sorting in the table

**Comment by DiRaiks** [comment]
> Looks good, but sorting doesn't work, or maybe the stories example is not correct, and we can’t see sorting in the table

The table is a presentation layer - sorting in the component is only visual, sorting itself must be implemented where the table will be used. For example, through API requests. The table only displays which field is sorted and by what principle (ASC, DESC)

**Comment by DiRaiks** [comment]
chip

**Review by karinamaulitova — APPROVED** [review]

**Review by kozlovzxc-at-lido — APPROVED** [review]
Looks good, thanks for gifs! Please notify Stan about that, and it's good to be merged 👌

**Pull request merged**
